// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        // Not configured for macOS; local edge builds skip Firebase in main.dart.
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQduaHGf6FI5M89wEQmQ35K5Eo04A6WnU',
    appId: '1:30841056766:web:ec5096088ecd16b237e4af',
    messagingSenderId: '30841056766',
    projectId: 'eburon-bd040',
    authDomain: 'eburon-bd040.firebaseapp.com',
    databaseURL:
        'https://eburon-bd040-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eburon-bd040.firebasestorage.app',
    measurementId: 'G-GRN6HYJNC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2nyZADDl9oq501-t4ZDt9q2Ru9zOUjWo',
    appId: '1:30841056766:android:fa20cddb5bd0e83537e4af',
    messagingSenderId: '30841056766',
    projectId: 'eburon-bd040',
    databaseURL:
        'https://eburon-bd040-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eburon-bd040.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrDf_v9YPl_laljzG4S9SGxZilmRhmWMg',
    appId: '1:30841056766:ios:2e86a365e310af3337e4af',
    messagingSenderId: '30841056766',
    projectId: 'eburon-bd040',
    databaseURL:
        'https://eburon-bd040-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'eburon-bd040.firebasestorage.app',
    androidClientId:
        '30841056766-4sd0lv6i3c9p387msfsl8v1ncu9q1sq6.apps.googleusercontent.com',
    iosClientId:
        '30841056766-0pedlvuepuagcvo610te50k46kjoh8ns.apps.googleusercontent.com',
    iosBundleId: 'ai.eburon.dualtranslate',
  );
}
